# Change these first
owner: lexiandev # Your GitHub organization or username, where this repository lives
repo: status.lexian.dev # The name of this repository

sites:
  - name: LexianDEV
    url: https://www.lexian.dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.lexian.dev
  baseUrl: /status.lexian.dev
  logoUrl: https://raw.githubusercontent.com/LexianDEV/status.lexian.dev/master/assets/logo.svg
  name: Uptime
  introTitle: "Welcome to **status.lexian.dev**"
  introMessage: This is the status page for core services such as LexianAPP and LexianDEV portfolio website, as well as other services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
